export default {
  default: {
    light: {
      '--border': '0 0 80%',
      '--background': '0 0 100%',
      '--foreground': '0 0 0%',
      '--primary': '200 50% 50%',
      '--primary-foreground': '0 0 0%',
      '--secondary': '0 0 80%',
      '--secondary-foreground': '0 0 20%',
      '--main-area-bg': '0 0 90%',
    },
    dark: {
      '--border': '0 0 20%',
      '--background': '0 0 0%',
      '--foreground': '#fff',
      '--primary': '#529ef4',
      '--primary-foreground': '#fff',
      '--secondary': '#292929',
      '--secondary-foreground': '#fff',
      '--main-area-bg': '#000',
    },
  },
  red: {
    light: {
      '--border': '#dcdfe6',
      '--background': '#fff',
      '--foreground': '#000',
      '--primary': '#dc2727',
      '--primary-foreground': '#000',
      '--secondary': '#e5e7eb',
      '--secondary-foreground': '#000',
      '--main-area-bg': '#f5f5f5',
    },
    dark: {
      '--border': '#4c4d4f',
      '--background': '#000',
      '--foreground': '#fff',
      '--primary': '#dc2727',
      '--primary-foreground': '#000',
      '--secondary': '#292929',
      '--secondary-foreground': '#fff',
      '--main-area-bg': '#000',
    },
  },
}
